default: &default
  adapter: mysql2
  encoding: utf8
  pool: 20
  username: root
  password: thanhbang
  host: localhost

development:
  <<: *default
  database: login_app_development
  
test:
  <<: *default
  database: login_app_test
  
production:
  <<: *default
  database: login_app_production
  username: login_app
  password: <%= ENV['LOGIN_APP_DATABASE_PASSWORD'] %>
